Vagrant.configure("2") do |config|
  config.vm.box = "kumokay/ubuntu16_react"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 3000, host: 3333
end
