apiVersion: v1
kind: Service
metadata:
  name: payment-mysql
  labels:
    app: payment
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: payment
    tier: mysql
# clusterIP: None

