apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mysql-pv-claim
  labels:
    app: payment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

