# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: bid
  labels:
    app: bid
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 50051
  selector:
    app: bid
    tier: backend
