# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bid
        tier: backend
  template:
    metadata:
      labels:
        app: bid
        tier: backend
    spec:
      containers:
      - name: bid
        image: kumokay/bidding:latest
        command: ["python3", "async_bidding_server.py"]
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50051
