Vagrant.configure("2") do |config|
  config.vm.box = "kumokay/ubuntu16_react"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 4000, host: 4444
  #copy sample code
  config.vm.provision "copy graphql_helloworld", type: "file",
    source: "graphql_helloworld", destination: "~/graphql_helloworld"
  config.vm.provision "copy graphql_helloworld_rewrite", type: "file",
    source: "graphql_helloworld_rewrite", destination: "~/graphql_helloworld_rewrite"
  config.vm.provision "copy graphql_starwars", type: "file",
    source: "graphql_starwars", destination: "~/graphql_starwars"
end
