apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: user-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: user-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: user-mysql-pv-claim

