apiVersion: v1
kind: Service
metadata:
  name: user-mysql
  labels:
    app: user
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: user
    tier: mysql
# clusterIP: None

