apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-mysql-pv-claim
  labels:
    app: product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

