apiVersion: v1
kind: Service
metadata:
  name: product-mysql
  labels:
    app: product
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: product
    tier: mysql
# clusterIP: None

