apiVersion: v1
kind: Service
metadata:
  name: auction-mysql
  labels:
    app: auction
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: auction
    tier: mysql
# clusterIP: None

