apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auction-mysql-pv-claim
  labels:
    app: auction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

