# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
        app: greeter
        tier: backend
  template:
    metadata:
      labels:
        app: greeter
        tier: backend
    spec:
      containers:
      - name: greetserver
        image: kumokay/greetserver:latest
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50051
